feat : 장바구니 등록 기능 추가
sky1231234/cafe-order pull request #1
Opened 2024-04-04 08:30 UTC by sky1231234

2024-04-07 03:09 UTC, ryan-nomad requested changes
전반적으로 코드의 가독성이 향상되었네요 👍

✅ 다양한 케이스에 대해 테스트코를 작성하셨어요. 
✅ 그 외에 Junit 기능으로 중복을 피하는 등의 시도도 좋았어요.
✅ 하드코딩 보다는 enum, 상수 등으로 관리하는 부분도 많이 향상되었어요.

🙏🏻 커밋을 조금 더 세분화해서 꼼꼼하게 관리해야해요.
🙏🏻 네이밍(변수,메소드 등)할 때 조금 더 고민이 필요해보여요.
🙏🏻 Fixture에 대한 피드백은, 테스트 많이 해보면서 용도와 가독성에 대해 향상시키면 되니 크게 고민할 내용은 아니에요.

2024-04-08 06:19 UTC, sky1231234 commented on src/main/java/com/example/order/cafe/domain/CafeInfo.java
> +            throw new IllegalArgumentException(CafeInfoErrorMsg.CAFE_NAME_LENGTH_ERROR_MESSAGE.getValue());
에러메시지에 코드와 메시지를 함께 포함하려 했고,
둘 다 포함하도록 static final String 코드 = "메시지"로 정의하면 변수명인 코드가 어떠한 에러를 나타내는지 알 수 없어서 명확성이 떨어지는 것 같아 enum을 사용했습니다. 

더 고민해보겠습니다!

2024-04-10 02:32 UTC, ryan-nomad commented on src/main/java/com/example/order/cafe/domain/CafeInfo.java
> +            throw new IllegalArgumentException(CafeInfoErrorMsg.CAFE_NAME_LENGTH_ERROR_MESSAGE.getValue());
코드가 반영된다면 양선님 말씀처럼 enum이 좋을 것같아요. 리뷰 시점에 CafeInfoErrorMsg 안에는 메세지만 들어있었어서 말씀드렸습니다.

2024-04-10 02:37 UTC, ryan-nomad approved these changes
진행을 위한 PR 승인

2024-04-10 02:38 UTC, ryan-nomad approved these changes

2024-04-10 06:46 UTC, ryan-nomad approved these changes

2024-04-10 06:46 UTC, merged